### ISSUE TITLE
Change `/leads` route URL to `/forward-call`

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/call-tracking-rails#2]
It would be nice if the route Twilio uses for incoming calls had a nicer name.

Please change the URL for the `/leads` route to be `/forward-call` instead. Just renaming the URL is fine - everything in the controllers already has a good name.

Also - please add a sentence about this `/forward-call` URL to the TwiML Application part of the README. Developers will need to add this URL to their TwiML Application when they try out our app.

**Comment by acamino** [comment]
@atbaker I couldn't agree more about to have a nicer name for the URL, but I don't like the idea about to change the controller `LeadsController` to `ForwardCall` controller, mostly because I think given route should represent some resource.

I guess I can use the approach you used on Django tutorial, I mean to have a controller `CallTrackingController` and then to have the action `forward-call`, what do you think, so that the URL will be `call-tracking/forward-call`, what do you think?

**Comment by atbaker** [comment]
@acamino I like the idea of going with `call-tracking/forward-call` - let's do that!

**Comment by acamino** [comment]
@atbaker, please have a look at #4?

**Comment by atbaker** [comment]
Merged! We're all good here.
